#!/bin/sh

cd /src/

export DOORMAN_ENV=prod
export DOORMAN_SETTINGS=$PWD/settings.cfg

exec chpst \
  -u doorman \
  -U doorman \
  python serv.py
#  twistd web --wsgi
#  gunicorn \
#    --workers 4 \
#    --bind 0.0.0.0:5000 \
#    manage:app \
#    --certfile=cert.pem\
#    --keyfile=privkey.pem\
#    --ssl-version 5 \
#    --ciphers TLSv1
